# Generated by Django 2.1.3 on 2018-11-16 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='paradigm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='languages.Paradigm'),
        ),
        migrations.AddField(
            model_name='programmer',
            name='languages',
            field=models.ManyToManyField(to='languages.Language'),
        ),
    ]
